### ISSUE TITLE
Import leitan/zustand

### ISSUE THREAD

**Issue by bvasquezm** [Hecmatyar/leiten-zustand#1]
Hi! Great job with the library, I've already seen the code and I'm sure it will help plenty of people like me.
Is it available for use? and if the answer is yes, how can I import it inside my project? Is it `import 'leitan/zustand'`

Again, congratulations and keep going!

**Comment by Hecmatyar** [comment]
Hi,  here
Hi. The library already comes with types if needed. [here](https://codesandbox.io/p/sandbox/bitter-lake-w57ywe?selection=%5B%7B%22endColumn%22%3A44%2C%22endLineNumber%22%3A49%2C%22startColumn%22%3A44%2C%22startLineNumber%22%3A49%7D%5D&file=%2Fsrc%2Frequest%2FRequest.tsx) is an example how to use it.
And about function import
`import {
  leitenRequest,
  leitenGroupRequest,
  ILeitenGroupRequestParams,
  leitenList,
  leitenRecord,
  leitenModal,
  leitenNormalizedList,
  leitenPrimitive,
  leitenContext,
  ...
} from "leiten-zustand";
`

Hope I understood the question correctly.

**Comment by bvasquezm** [comment]
Thanks for the prompt reply! I'll take a look to the example and try to import it the way you are showing me.
